import {
  Bitcoin,
  TrendingUp,
  TrendingDown,
  LineChart,
  BarChart3,
  CreditCard,
  Home,
  Heart,
  HeartCrack,
  ShieldAlert,
  ShieldOff,
  Sparkles,
  Landmark,
  MonitorX,
  Wallet,
  Coins,
  ShieldCheck,
  Activity,
  Search,
  Stethoscope,
  Briefcase,
  Scale,
  Lock,
  Unlock,
  UserX,
  Smartphone,
  Laptop,
  CloudOff,
  GanttChart,
  Hammer,
  Gavel,
  History,
  FileSearch,
  MailQuestion,
  Fingerprint,
  Users2,
  HardDriveDownload,
  AlertTriangle,
  Zap,
  CheckCircle2,
  ShieldQuestion,
  SearchCode,
  ShieldBan,
  DatabaseZap,
  Globe2,
  Network,
  Cpu,
  Trophy,
  Award,
  BadgeCheck,
  ShieldEllipsis,
  MessageCircleOff,
  SmartphoneNfc,
  Ghost,
  EyeOff,
  Crosshair,
  TimerReset,
  Microscope,
  Binary,
  Bot,
  Boxes,
  Code2,
  Fingerprint as FingerprintIcon,
  ShieldCheck as ShieldCheckIcon,
  Unlock as UnlockIcon,
  UserMinus,
  Construction,
  ShieldAlert as ShieldAlertIcon,
  Skull,
  Siren,
  Terminal,
  Activity as ActivityIcon,
  BarChart3 as BarChartIcon,
  Briefcase as BriefcaseIcon,
  Calendar as CalendarIcon,
  CheckCircle2 as CheckCircleIcon,
  ClipboardList as ClipboardIcon,
  Clock as ClockIcon,
  CreditCard as CreditCardIcon,
  Database as DatabaseIcon,
  Eye as EyeIcon,
  FileText as FileIcon,
  Globe as GlobeIcon,
  Heart as HeartIcon,
  Home as HomeIcon,
  Image as ImageIcon,
  LayoutDashboard as LayoutIcon,
  Link2 as LinkIcon,
  Lock as LockIcon,
  Mail as MailIcon,
  MessageSquare as MessageSquareIcon,
  Moon as MoonIcon,
  Phone as PhoneIcon,
  Play as PlayIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Share2 as ShareIcon,
  Shield as ShieldIcon,
  Star as StarIcon,
  Sun as SunIcon,
  Trash2 as TrashIcon,
  User as UserIcon,
  Video as VideoIcon,
  XCircle as XCircleIcon,
  Zap as ZapIcon,
  DollarSign,
  type LucideIcon,
  ClipboardList,
  Trash2,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  Bitcoin,
  TrendingUp,
  TrendingDown,
  LineChart,
  BarChart3,
  CreditCard,
  Home,
  Heart,
  HeartCrack,
  ShieldAlert,
  ShieldOff,
  Sparkles,
  Landmark,
  MonitorX,
  Wallet,
  Coins,
  ShieldCheck,
  Activity,
  Search,
  Stethoscope,
  Briefcase,
  Scale,
  Lock,
  Unlock,
  UserX,
  Smartphone,
  Laptop,
  CloudOff,
  GanttChart,
  Hammer,
  Gavel,
  History,
  FileSearch,
  MailQuestion,
  Fingerprint,
  Users2,
  HardDriveDownload,
  AlertTriangle,
  Zap,
  CheckCircle2,
  ShieldQuestion,
  SearchCode,
  ShieldBan,
  DatabaseZap,
  Globe2,
  Network,
  Cpu,
  Trophy,
  Award,
  BadgeCheck,
  ShieldEllipsis,
  MessageCircleOff,
  SmartphoneNfc,
  Ghost,
  EyeOff,
  Crosshair,
  TimerReset,
  Microscope,
  Binary,
  Bot,
  Boxes,
  Code2,
  FingerprintIcon,
  ShieldCheckIcon,
  UnlockIcon,
  UserMinus,
  Construction,
  ShieldAlertIcon,
  Skull,
  Siren,
  Terminal,
  ActivityIcon,
  BarChartIcon,
  BriefcaseIcon,
  CalendarIcon,
  CheckCircleIcon,
  ClipboardIcon,
  ClockIcon,
  CreditCardIcon,
  DatabaseIcon,
  EyeIcon,
  FileIcon,
  GlobeIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  LayoutIcon,
  LinkIcon,
  LockIcon,
  MailIcon,
  MessageSquareIcon,
  MoonIcon,
  PhoneIcon,
  PlayIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  StarIcon,
  SunIcon,
  TrashIcon,
  UserIcon,
  VideoIcon,
  XCircleIcon,
  ZapIcon,
  FileText: FileIcon,
  DollarSign,
};

/**
 * Renders a premium 3D-style icon tile. The icon is resolved from a string
 * name (matches lucide-react export), with a sensible fallback.
 */
export function ServiceIcon({ name, className = "" }: { name?: string | null; className?: string }) {
  const Icon = (name && map[name]) || Sparkles;
  return (
    <div
      className={`relative h-14 w-14 rounded-2xl flex items-center justify-center text-white shadow-elegant ${className}`}
      style={{
        background: "var(--gradient-cta)",
        transform: "translateZ(0)",
      }}
    >
      <span
        aria-hidden
        className="absolute inset-0 rounded-2xl"
        style={{
          background: "linear-gradient(135deg, rgba(255,255,255,0.45), rgba(255,255,255,0) 55%)",
          mixBlendMode: "overlay",
        }}
      />
      <Icon className="w-7 h-7 relative drop-shadow" strokeWidth={2.2} />
    </div>
  );
}
