/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTestimonialsRouteImport } from './routes/_site.testimonials'
import { Route as SiteSuccessCalculatorRouteImport } from './routes/_site.success-calculator'
import { Route as SitePrivacyPolicyRouteImport } from './routes/_site.privacy-policy'
import { Route as SiteLoansRouteImport } from './routes/_site.loans'
import { Route as SiteDashboardRouteImport } from './routes/_site.dashboard'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteBlogIndexRouteImport } from './routes/_site.blog.index'
import { Route as SiteServicesSlugRouteImport } from './routes/_site.services.$slug'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'

const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTestimonialsRoute = SiteTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSuccessCalculatorRoute = SiteSuccessCalculatorRouteImport.update({
  id: '/success-calculator',
  path: '/success-calculator',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyPolicyRoute = SitePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoansRoute = SiteLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDashboardRoute = SiteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesSlugRoute = SiteServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-api': typeof TestApiRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/dashboard': typeof SiteDashboardRoute
  '/loans': typeof SiteLoansRoute
  '/privacy-policy': typeof SitePrivacyPolicyRoute
  '/success-calculator': typeof SiteSuccessCalculatorRoute
  '/testimonials': typeof SiteTestimonialsRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/blog/': typeof SiteBlogIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-api': typeof TestApiRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/dashboard': typeof SiteDashboardRoute
  '/loans': typeof SiteLoansRoute
  '/privacy-policy': typeof SitePrivacyPolicyRoute
  '/success-calculator': typeof SiteSuccessCalculatorRoute
  '/testimonials': typeof SiteTestimonialsRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/blog': typeof SiteBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-api': typeof TestApiRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/dashboard': typeof SiteDashboardRoute
  '/_site/loans': typeof SiteLoansRoute
  '/_site/privacy-policy': typeof SitePrivacyPolicyRoute
  '/_site/success-calculator': typeof SiteSuccessCalculatorRoute
  '/_site/testimonials': typeof SiteTestimonialsRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/services/$slug': typeof SiteServicesSlugRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/test-api'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/loans'
    | '/privacy-policy'
    | '/success-calculator'
    | '/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/test-api'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/loans'
    | '/privacy-policy'
    | '/success-calculator'
    | '/testimonials'
    | '/'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/test-api'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/dashboard'
    | '/_site/loans'
    | '/_site/privacy-policy'
    | '/_site/success-calculator'
    | '/_site/testimonials'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/services/$slug'
    | '/_site/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestApiRoute: typeof TestApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/testimonials': {
      id: '/_site/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof SiteTestimonialsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/success-calculator': {
      id: '/_site/success-calculator'
      path: '/success-calculator'
      fullPath: '/success-calculator'
      preLoaderRoute: typeof SiteSuccessCalculatorRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy-policy': {
      id: '/_site/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof SitePrivacyPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/loans': {
      id: '/_site/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof SiteLoansRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/dashboard': {
      id: '/_site/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SiteDashboardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/$slug': {
      id: '/_site/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof SiteServicesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDashboardRoute: typeof SiteDashboardRoute
  SiteLoansRoute: typeof SiteLoansRoute
  SitePrivacyPolicyRoute: typeof SitePrivacyPolicyRoute
  SiteSuccessCalculatorRoute: typeof SiteSuccessCalculatorRoute
  SiteTestimonialsRoute: typeof SiteTestimonialsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteServicesSlugRoute: typeof SiteServicesSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDashboardRoute: SiteDashboardRoute,
  SiteLoansRoute: SiteLoansRoute,
  SitePrivacyPolicyRoute: SitePrivacyPolicyRoute,
  SiteSuccessCalculatorRoute: SiteSuccessCalculatorRoute,
  SiteTestimonialsRoute: SiteTestimonialsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteServicesSlugRoute: SiteServicesSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestApiRoute: TestApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
