/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SuccessCalculatorRouteImport } from './routes/success-calculator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiLoanApplicationsRouteImport } from './routes/api/loan-applications'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiAdminTestimonialsRouteImport } from './routes/api/admin/testimonials'
import { Route as ApiAdminLoansRouteImport } from './routes/api/admin/loans'
import { Route as ApiAdminLeadsRouteImport } from './routes/api/admin/leads'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessCalculatorRoute = SuccessCalculatorRouteImport.update({
  id: '/success-calculator',
  path: '/success-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoanApplicationsRoute = ApiLoanApplicationsRouteImport.update({
  id: '/api/loan-applications',
  path: '/api/loan-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestimonialsRoute = ApiAdminTestimonialsRouteImport.update({
  id: '/api/admin/testimonials',
  path: '/api/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoansRoute = ApiAdminLoansRouteImport.update({
  id: '/api/admin/loans',
  path: '/api/admin/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLeadsRoute = ApiAdminLeadsRouteImport.update({
  id: '/api/admin/leads',
  path: '/api/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/loans': typeof LoansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-calculator': typeof SuccessCalculatorRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/loan-applications': typeof ApiLoanApplicationsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/loans': typeof ApiAdminLoansRoute
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/loans': typeof LoansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-calculator': typeof SuccessCalculatorRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/loan-applications': typeof ApiLoanApplicationsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/loans': typeof ApiAdminLoansRoute
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/loans': typeof LoansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-calculator': typeof SuccessCalculatorRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/loan-applications': typeof ApiLoanApplicationsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/loans': typeof ApiAdminLoansRoute
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/loans'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/success-calculator'
    | '/testimonials'
    | '/api/leads'
    | '/api/loan-applications'
    | '/services/$slug'
    | '/api/admin/leads'
    | '/api/admin/loans'
    | '/api/admin/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/loans'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/success-calculator'
    | '/testimonials'
    | '/api/leads'
    | '/api/loan-applications'
    | '/services/$slug'
    | '/api/admin/leads'
    | '/api/admin/loans'
    | '/api/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/loans'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/success-calculator'
    | '/testimonials'
    | '/api/leads'
    | '/api/loan-applications'
    | '/services/$slug'
    | '/api/admin/leads'
    | '/api/admin/loans'
    | '/api/admin/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  LoansRoute: typeof LoansRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessCalculatorRoute: typeof SuccessCalculatorRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLoanApplicationsRoute: typeof ApiLoanApplicationsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ApiAdminLeadsRoute: typeof ApiAdminLeadsRoute
  ApiAdminLoansRoute: typeof ApiAdminLoansRoute
  ApiAdminTestimonialsRoute: typeof ApiAdminTestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-calculator': {
      id: '/success-calculator'
      path: '/success-calculator'
      fullPath: '/success-calculator'
      preLoaderRoute: typeof SuccessCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loan-applications': {
      id: '/api/loan-applications'
      path: '/api/loan-applications'
      fullPath: '/api/loan-applications'
      preLoaderRoute: typeof ApiLoanApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/testimonials': {
      id: '/api/admin/testimonials'
      path: '/api/admin/testimonials'
      fullPath: '/api/admin/testimonials'
      preLoaderRoute: typeof ApiAdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/loans': {
      id: '/api/admin/loans'
      path: '/api/admin/loans'
      fullPath: '/api/admin/loans'
      preLoaderRoute: typeof ApiAdminLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/leads': {
      id: '/api/admin/leads'
      path: '/api/admin/leads'
      fullPath: '/api/admin/leads'
      preLoaderRoute: typeof ApiAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  LoansRoute: LoansRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessCalculatorRoute: SuccessCalculatorRoute,
  TestimonialsRoute: TestimonialsRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLoanApplicationsRoute: ApiLoanApplicationsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ApiAdminLeadsRoute: ApiAdminLeadsRoute,
  ApiAdminLoansRoute: ApiAdminLoansRoute,
  ApiAdminTestimonialsRoute: ApiAdminTestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
