-- Seed 100+ testimonials (all amounts >= $50,000)
insert into public.testimonials (client_name, location, rating, quote, amount_recovered, scam_type, is_published, is_featured, sort_order) values
('Brenda D.', 'London, UK', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '£805,880', 'Stock Trading', true, false, 0),
('Rachel B.', 'Cairo, Egypt', 5, 'From the free consultation to the final payout, the team was outstanding.', '$88,346', 'Binary Options', true, false, 1),
('Eric Y.', 'Houston, USA', 5, 'Their blockchain analysts are the real deal. Traced the funds across five wallets.', '$468,079', 'Stock Trading', true, false, 2),
('Jacob E.', 'Dublin, Ireland', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$375,838', 'Ponzi Scheme', true, false, 3),
('Eric F.', 'Nairobi, Kenya', 5, 'From the free consultation to the final payout, the team was outstanding.', '$562,986', 'Online Trading Scam', true, false, 4),
('Joe E.', 'Manila, Philippines', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$488,181', 'Stock Trading', true, false, 5),
('Christian Y.', 'Melbourne, Australia', 5, 'From the free consultation to the final payout, the team was outstanding.', '$788,197', 'Forex', true, false, 6),
('Maria L.', 'Warsaw, Poland', 4, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '$258,917', 'Ponzi Scheme', true, false, 7),
('Noah N.', 'Toronto, Canada', 5, 'They explained the recovery process in plain English and delivered on every promise.', '$698,284', 'Binary Options', true, false, 8),
('Kenneth B.', 'Riyadh, KSA', 5, 'From the free consultation to the final payout, the team was outstanding.', '$408,302', 'Online Trading Scam', true, false, 9),
('Rebecca Y.', 'Riyadh, KSA', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$346,092', 'Ponzi Scheme', true, false, 10),
('Barbara W.', 'Lagos, Nigeria', 5, 'I reported the scam to police and nothing happened. ChanAidRecovery made the recovery happen.', '$539,240', 'Property Scams', true, false, 11),
('Nicole Z.', 'Phoenix, USA', 5, 'I reported the scam to police and nothing happened. ChanAidRecovery made the recovery happen.', '£149,711', 'Online Trading Scam', true, false, 12),
('Sophia O.', 'Buenos Aires, Argentina', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '£704,467', 'Credit Card Phishing', true, false, 13),
('Megan R.', 'Kuala Lumpur, Malaysia', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '€128,995', 'Forex', true, true, 14),
('Jerry H.', 'Cairo, Egypt', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$747,830', 'Binary Options', true, true, 15),
('Catherine Z.', 'Copenhagen, Denmark', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '£800,920', 'Fake Investment Platform', true, false, 16),
('Hannah J.', 'Tel Aviv, Israel', 5, 'Transparent pricing, clear updates, and a real legal strategy. Worth every penny.', '$228,305', 'Stock Trading', true, false, 17),
('Joan T.', 'Austin, USA', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '$278,558', 'Stock Trading', true, false, 18),
('Edward R.', 'Manchester, UK', 4, 'I reported the scam to police and nothing happened. ChanAidRecovery made the recovery happen.', '$137,974', 'Romance Scams', true, false, 19),
('Justin S.', 'New York, USA', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '$574,277', 'Romance Scams', true, false, 20),
('Joseph A.', 'Chicago, USA', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$110,708', 'Fake Investment Platform', true, false, 21),
('Thomas Y.', 'Warsaw, Poland', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '$773,525', 'Online Trading Scam', true, false, 22),
('Cynthia H.', 'Manila, Philippines', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '$457,527', 'Romance Scams', true, false, 23),
('Brenda S.', 'Manchester, UK', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$486,476', 'Cryptocurrency', true, false, 24),
('Jacqueline B.', 'Munich, Germany', 5, 'They knew exactly which exchanges to subpoena. Full refund plus damages — I still cannot believe it.', '£626,347', 'Cryptocurrency', true, false, 25),
('Brenda R.', 'Kuala Lumpur, Malaysia', 5, 'After being scammed I was devastated. ChanAidRecovery restored my finances and my dignity.', '$768,642', 'Binary Options', true, true, 26),
('Steven M.', 'Taipei, Taiwan', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$599,962', 'Stock Trading', true, false, 27),
('Samantha P.', 'Auckland, NZ', 5, 'Transparent pricing, clear updates, and a real legal strategy. Worth every penny.', '$822,773', 'Stock Trading', true, false, 28),
('Eric D.', 'Bangkok, Thailand', 5, 'They explained the recovery process in plain English and delivered on every promise.', '€267,055', 'Forex', true, false, 29),
('Janet P.', 'Phoenix, USA', 5, 'They knew exactly which exchanges to subpoena. Full refund plus damages — I still cannot believe it.', '$509,776', 'Stock Trading', true, false, 30),
('Austin W.', 'Houston, USA', 5, 'They knew exactly which exchanges to subpoena. Full refund plus damages — I still cannot believe it.', '€621,519', 'Binary Options', true, false, 31),
('Mark E.', 'Bangkok, Thailand', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '$200,718', 'Cryptocurrency', true, true, 32),
('Victoria N.', 'Dublin, Ireland', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '£249,391', 'Cryptocurrency', true, false, 33),
('James D.', 'Seoul, South Korea', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '$256,756', 'Fake Investment Platform', true, false, 34),
('Kathryn T.', 'Seoul, South Korea', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '€744,107', 'Binary Options', true, false, 35),
('Joseph K.', 'Mumbai, India', 5, 'Their blockchain analysts are the real deal. Traced the funds across five wallets.', '$81,043', 'Binary Options', true, false, 36),
('Teresa T.', 'Lisbon, Portugal', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '$757,793', 'Credit Card Phishing', true, false, 37),
('Shirley B.', 'Prague, Czechia', 5, 'They explained the recovery process in plain English and delivered on every promise.', '$398,440', 'Forex', true, false, 38),
('Jacob M.', 'Prague, Czechia', 4, 'My savings came back to me thanks to their global network. Highly recommended.', '£82,585', 'Binary Options', true, false, 39),
('Kathryn Z.', 'Austin, USA', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$689,754', 'Binary Options', true, false, 40),
('Laura Z.', 'Bangkok, Thailand', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$706,098', 'Online Trading Scam', true, false, 41),
('Pamela S.', 'London, UK', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '£359,932', 'Ponzi Scheme', true, false, 42),
('Sarah E.', 'Paris, France', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '$216,485', 'Stock Trading', true, false, 43),
('David M.', 'Sydney, Australia', 5, 'After being scammed I was devastated. ChanAidRecovery restored my finances and my dignity.', '$695,784', 'Ponzi Scheme', true, false, 44),
('Nancy E.', 'Mumbai, India', 4, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$473,683', 'Romance Scams', true, false, 45),
('Laura L.', 'Singapore', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '$507,143', 'Ponzi Scheme', true, false, 46),
('Gloria O.', 'Copenhagen, Denmark', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '£222,062', 'Credit Card Phishing', true, true, 47),
('Joyce K.', 'Edinburgh, UK', 4, 'From the free consultation to the final payout, the team was outstanding.', '$642,117', 'Online Trading Scam', true, false, 48),
('Charles Y.', 'Zurich, Switzerland', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '€304,594', 'Stock Trading', true, false, 49),
('Emma L.', 'Nairobi, Kenya', 5, 'I reported the scam to police and nothing happened. ChanAidRecovery made the recovery happen.', '$487,338', 'Ponzi Scheme', true, false, 50),
('Stephanie Y.', 'Istanbul, Türkiye', 5, 'Transparent pricing, clear updates, and a real legal strategy. Worth every penny.', '€171,179', 'Forex', true, false, 51),
('Pamela Z.', 'London, UK', 5, 'I thought the money was gone forever. Their investigators proved otherwise and kept me informed every step.', '$671,600', 'Ponzi Scheme', true, false, 52),
('Margaret J.', 'Tel Aviv, Israel', 5, 'From the free consultation to the final payout, the team was outstanding.', '$159,500', 'Cryptocurrency', true, false, 53),
('Virginia A.', 'Oslo, Norway', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '$279,636', 'Online Trading Scam', true, false, 54),
('Christine A.', 'Johannesburg, SA', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '€406,973', 'Credit Card Phishing', true, false, 55),
('Laura Y.', 'Melbourne, Australia', 4, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '€142,808', 'Property Scams', true, true, 56),
('Hannah Y.', 'Madrid, Spain', 5, 'From the free consultation to the final payout, the team was outstanding.', '$126,415', 'Binary Options', true, false, 57),
('Susan Z.', 'Phoenix, USA', 5, 'I reported the scam to police and nothing happened. ChanAidRecovery made the recovery happen.', '$483,429', 'Binary Options', true, false, 58),
('Amanda D.', 'Tokyo, Japan', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '$121,103', 'Stock Trading', true, false, 59),
('Arthur N.', 'Prague, Czechia', 5, 'I thought the money was gone forever. Their investigators proved otherwise and kept me informed every step.', '€637,384', 'Fake Investment Platform', true, false, 60),
('Jonathan S.', 'Chicago, USA', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '£789,033', 'Ponzi Scheme', true, true, 61),
('Christian Z.', 'Oslo, Norway', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '€149,320', 'Online Trading Scam', true, true, 62),
('Betty B.', 'Edinburgh, UK', 5, 'They explained the recovery process in plain English and delivered on every promise.', '€121,628', 'Property Scams', true, false, 63),
('Carol J.', 'Singapore', 4, 'Kind, patient, and effective. They treated me like family, not a case number.', '$700,010', 'Online Trading Scam', true, false, 64),
('Stephanie O.', 'Doha, Qatar', 5, 'They knew exactly which exchanges to subpoena. Full refund plus damages — I still cannot believe it.', '$423,643', 'Property Scams', true, false, 65),
('Eric H.', 'Johannesburg, SA', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$192,169', 'Credit Card Phishing', true, false, 66),
('Stephanie H.', 'Kuala Lumpur, Malaysia', 4, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$369,096', 'Romance Scams', true, false, 67),
('Sharon G.', 'Munich, Germany', 4, 'Transparent pricing, clear updates, and a real legal strategy. Worth every penny.', '$71,369', 'Romance Scams', true, false, 68),
('Stephanie G.', 'Sydney, Australia', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '$716,788', 'Credit Card Phishing', true, false, 69),
('Melissa E.', 'Stockholm, Sweden', 5, 'I thought the money was gone forever. Their investigators proved otherwise and kept me informed every step.', '€121,527', 'Credit Card Phishing', true, false, 70),
('Dennis H.', 'Boston, USA', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '€630,649', 'Online Trading Scam', true, false, 71),
('Samuel S.', 'Kuala Lumpur, Malaysia', 5, 'Their blockchain analysts are the real deal. Traced the funds across five wallets.', '$358,036', 'Romance Scams', true, false, 72),
('Amanda N.', 'Vienna, Austria', 5, 'From the free consultation to the final payout, the team was outstanding.', '$520,163', 'Ponzi Scheme', true, false, 73),
('Brian R.', 'Prague, Czechia', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '$783,018', 'Credit Card Phishing', true, false, 74),
('Sara H.', 'Perth, Australia', 4, 'Transparent pricing, clear updates, and a real legal strategy. Worth every penny.', '€633,901', 'Forex', true, false, 75),
('Abigail S.', 'Madrid, Spain', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '$462,577', 'Fake Investment Platform', true, false, 76),
('Jennifer V.', 'Buenos Aires, Argentina', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '€472,223', 'Ponzi Scheme', true, false, 77),
('Olivia O.', 'Melbourne, Australia', 5, 'I thought the money was gone forever. Their investigators proved otherwise and kept me informed every step.', '€93,457', 'Binary Options', true, false, 78),
('Keith J.', 'Kuala Lumpur, Malaysia', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '€135,078', 'Ponzi Scheme', true, false, 79),
('Steven S.', 'Taipei, Taiwan', 5, 'After being scammed I was devastated. ChanAidRecovery restored my finances and my dignity.', '$620,209', 'Ponzi Scheme', true, false, 80),
('Walter V.', 'Edinburgh, UK', 5, 'They knew exactly which exchanges to subpoena. Full refund plus damages — I still cannot believe it.', '£595,054', 'Credit Card Phishing', true, false, 81),
('Heather E.', 'Riyadh, KSA', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '$54,606', 'Credit Card Phishing', true, false, 82),
('Joseph G.', 'Auckland, NZ', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '€507,215', 'Online Trading Scam', true, false, 83),
('Aaron B.', 'Singapore', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '$471,366', 'Fake Investment Platform', true, false, 84),
('Kathleen M.', 'Kuala Lumpur, Malaysia', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '$117,315', 'Stock Trading', true, false, 85),
('Sean H.', 'Vancouver, Canada', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '€633,509', 'Fake Investment Platform', true, true, 86),
('Catherine O.', 'Los Angeles, USA', 5, 'From the free consultation to the final payout, the team was outstanding.', '$206,337', 'Binary Options', true, true, 87),
('Sophia P.', 'Vancouver, Canada', 5, 'They knew exactly which exchanges to subpoena. Full refund plus damages — I still cannot believe it.', '$272,538', 'Online Trading Scam', true, false, 88),
('Richard P.', 'Chicago, USA', 5, 'ChanAidRecovery was relentless. Within weeks they traced the wallet and recovered every cent I had lost.', '£750,030', 'Cryptocurrency', true, false, 89),
('Christina B.', 'London, UK', 5, 'I thought the money was gone forever. Their investigators proved otherwise and kept me informed every step.', '$149,580', 'Cryptocurrency', true, false, 90),
('Christian T.', 'Taipei, Taiwan', 4, 'After being scammed I was devastated. ChanAidRecovery restored my finances and my dignity.', '$516,178', 'Ponzi Scheme', true, true, 91),
('Andrea O.', 'Tel Aviv, Israel', 5, 'They handled the bank chargeback flawlessly and pushed for punitive damages on top.', '$144,775', 'Fake Investment Platform', true, false, 92),
('Justin C.', 'Madrid, Spain', 5, 'I reported the scam to police and nothing happened. ChanAidRecovery made the recovery happen.', '$542,674', 'Binary Options', true, false, 93),
('Daniel V.', 'Seattle, USA', 5, 'From the free consultation to the final payout, the team was outstanding.', '€225,053', 'Online Trading Scam', true, false, 94),
('Diane S.', 'Los Angeles, USA', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '€841,169', 'Online Trading Scam', true, false, 95),
('Julie K.', 'Taipei, Taiwan', 5, 'Their blockchain analysts are the real deal. Traced the funds across five wallets.', '$766,905', 'Binary Options', true, false, 96),
('Cheryl O.', 'Dublin, Ireland', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '$374,483', 'Cryptocurrency', true, false, 97),
('Michelle L.', 'Cairo, Egypt', 5, 'They explained the recovery process in plain English and delivered on every promise.', '€260,270', 'Stock Trading', true, false, 98),
('Cheryl T.', 'Copenhagen, Denmark', 4, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '$724,274', 'Online Trading Scam', true, false, 99),
('Stephen H.', 'Oslo, Norway', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '$603,913', 'Property Scams', true, false, 100),
('Dennis T.', 'Brisbane, Australia', 5, 'My savings came back to me thanks to their global network. Highly recommended.', '$293,255', 'Property Scams', true, false, 101),
('Carol S.', 'Copenhagen, Denmark', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$621,086', 'Stock Trading', true, false, 102),
('Frances D.', 'Dublin, Ireland', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '$305,491', 'Credit Card Phishing', true, true, 103),
('Jack E.', 'Madrid, Spain', 5, 'The team at ChanAidRecovery turned my nightmare around. I cannot thank them enough for their expertise.', '$542,313', 'Romance Scams', true, false, 104),
('Brandon O.', 'Edinburgh, UK', 5, 'After being scammed I was devastated. ChanAidRecovery restored my finances and my dignity.', '£789,083', 'Property Scams', true, false, 105),
('Gerald W.', 'Riyadh, KSA', 5, 'I was skeptical at first but the results speak for themselves. Fully recovered and more.', '$286,669', 'Stock Trading', true, false, 106),
('Edward E.', 'Riyadh, KSA', 5, 'Kind, patient, and effective. They treated me like family, not a case number.', '$517,276', 'Cryptocurrency', true, true, 107),
('Catherine J.', 'Los Angeles, USA', 5, 'Professional, calm, and decisive. They moved fast when other firms told me it was hopeless.', '$58,934', 'Romance Scams', true, false, 108),
('Kyle J.', 'Bangkok, Thailand', 5, 'They explained the recovery process in plain English and delivered on every promise.', '£345,176', 'Ponzi Scheme', true, false, 109);
