// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  // @ts-ignore
  const env = typeof process !== 'undefined' ? process.env : (typeof globalThis !== 'undefined' ? (globalThis as any).env : {});
  const SUPABASE_URL = env?.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = env?.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    if (typeof window === 'undefined') {
      console.warn('Supabase admin env vars missing during SSR, using mock.');
      const mockChain: any = () => new Proxy({}, {
        get: (target, prop) => {
          if (prop === 'then') return (cb: any) => Promise.resolve(cb({ data: null, error: null }));
          return mockChain;
        }
      });
      return new Proxy({} as any, {
        get: () => mockChain
      });
    }

    throw new Error(
      'Missing Supabase server environment variables. Ensure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
get(_, prop, receiver) {
  if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
  return Reflect.get(_supabaseAdmin, prop, receiver);
},
});
